
server.port: 8086
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
  bindings.input.consumer.application-id: word-count

spring.cloud.stream.bindings.output:
  destination: word_count_topic

spring.cloud.stream.bindings.input:
  destination: words_topic            